AllCops:
  Exclude:
    - gems/**/*
    - measures/**/*
    - spec/files/**/measures/**/*
require: rubocop-performance

inherit_from:
  - http://s3.amazonaws.com/openstudio-resources/styles/rubocop_v4.yml
