name: REopt-gem CI

on:
  workflow_dispatch:
  push:
  schedule:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    # 5:23 am UTC (11:23pm MDT the day before) every weekday night in MDT
    - cron: '23 5 * * 2-6'

env:
  # This env var should enforce develop branch of all dependencies
  FAVOR_LOCAL_GEMS: true
  GEM_DEVELOPER_KEY: ${{ secrets.GEM_DEVELOPER_KEY }}

jobs:
  weeknight-tests:
    # ubuntu-latest works since https://github.com/rbenv/ruby-build/releases/tag/v20220710 (July 10, 2022)
    # https://github.com/rbenv/ruby-build/discussions/1940
    runs-on: ubuntu-latest
    container:
      image: docker://nrel/openstudio:3.7.0
    steps:
      - uses: actions/checkout@v4
      - name: set git config options
        shell: bash
        run: |
          git config --global --add safe.directory '*'
      - name: Update gems
        run: |
          bundle update
          bundle exec certified-update
      - name: Run Rspec
        run: bundle exec rspec
      - name: Coveralls
        # coveralls action docs: https://github.com/marketplace/actions/coveralls-github-action
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: "./coverage/lcov/urbanopt-reopt-gem.lcov"
